version: '3.3'
services:
  react-builder:
    container_name: react-builder
    networks:
      - ws_proxy
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/app

  nginx:
    container_name: hanseifood_ws
    networks:
      - ws_proxy
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 8180:8180
    depends_on:
      - react-builder

networks:
  ws_proxy:
    external: true