services:
  react-builder:
    container_name: react-builder
    build:
      dockerfile: dockerfile
    volumes:
      - ./:/app
    depends_on:
      certbot:
        condition: service_healthy

  nginx:
    container_name: hanseifood_ws
    build:
      dockerfile: dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    restart: always
    ports:
      - 443:443

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    command: certonly --standalone -d hanseiweeklymenu.me --agree-tos -m tmd24710@naver.com
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '[-e "/etc/letsencrypt/live/hanseiweeklymenu.me/fullchain.pem"]',
        ]
      interval: 10s
      timeout: 2s
      retries: 100
