version: '3.3'
services:
  react-builder:
    container_name: react-builder
    build:
      dockerfile: dockerfile
    volumes:
      - ./:/app

  nginx:
    container_name: hanseifood_ws
    build:
      dockerfile: dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: command certonly --webroot -w /var/www/certbot -d hanseiweeklymenu.me --agree-tos --staging -m tmd24710@naver.com
    depends_on:
      - nginx
      - react-builder
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '[-e "/etc/letsencrypt/live/hanseiweeklymenu.me/fullchain.pem"]',
        ]
      interval: 10s
      timeout: 2s
