export { ReactComponent as cloche } from "./Cloche.svg";
export { ReactComponent as food } from "./Food.svg";
export { ReactComponent as chevron_left } from "./Chevron-left.svg";
export { ReactComponent as chevron_right } from "./Chevron-right.svg";
export { ReactComponent as plus } from "./Plus.svg";
export { ReactComponent as help } from "./Help.svg";
export { ReactComponent as about_me } from "./Person.svg";
export { ReactComponent as menu } from "./Menu.svg";
export { ReactComponent as home } from "./Home.svg";
